### ISSUE TITLE
Unable to verify authorization request state

### ISSUE THREAD

**Issue by naissa12** [auth0/passport-auth0#154]
I implemented google login using passport and nodejs. When I try to log in using google, I get the error "Unable to verify authorization request state.".

I added the following to my index.js code:

```
app.use (
    session ({
        secret: "ddd",
        resave: true,
        saveUninitialized: false,
        proxy: true,
        cookie: {
            expires: 60 * 60 * 24,
            secure: process.env.NODE_ENV === 'production'
        }
    })
);
if (app.get('env') === 'production') {
    app.set('trust proxy', 1); // trust first proxy
}
```

Can someone please help?

**Comment by adamjmcgrath** [comment]
Hi @naissa12 - I can't see anything wrong with your code.

When you get "Unable to verify authorization request state." it's usually because the cookies you've dropped at login don't match the cookies you pick up when you return to your app after login.

Can you share a HAR file that shows the login request and the login callback request, or can you share a running example that demonstrates the issue and we can debug it for you?

**Comment by corneliuslamb** [comment]
I am getting this as well.  The issue looks like you have to set state to a boolean.  If you set it as a string, like in my situation, under the hood the state parameter is not being stored in req.session.
